# This file describes an application. You can have multiple applications
# in the same project.

# The name of this app. Must be unique within a project.
name: swagbraintreeappinfrastructure

# The type of the application to build.
type: php:8.2

build:
  flavor: composer

dependencies:
  php:
    composer/composer: '^2'

runtime:
  extensions:
    - sodium

variables:
  env:
    # Tell Symfony to always install in production-mode.
    APP_NAME: SwagBraintreeApp
    APP_ENV: 'prod'
    APP_DEBUG: 0
    CORS_ALLOW_ORIGIN: '*'
    DATABASE_URL: mysql://user:@database.internal:3306/main

crons:
    snapshot:
        spec: 0 0 * * *
        cmd: |
            # only run for the production environment, aka trunk
            if [ "$PLATFORM_ENVIRONMENT_TYPE" = "production" ]; then
                croncape bin/console report:turnover
            fi

# The hooks that will be performed when the package is deployed.
hooks:
  build: |
    set -e
    npm install
    npm run build
  deploy: |
    set -e
    bin/console cache:clear
    bin/console doctrine:database:create --if-not-exists
    bin/console doctrine:migrations:migrate --no-interaction
# The relationships of the application with services or other applications.
# The left-hand side is the name of the relationship as it will be exposed
# to the application in the PLATFORM_RELATIONSHIPS variable. The right-hand
# side is in the form `<service name>:<endpoint name>`.
relationships:
  database: 'db:mysql'

# The size of the persistent disk of the application (in MB).
disk: 2048

# The mounts that will be performed when the package is deployed.
mounts:
  "/var":
    source: local
    source_path: "var"

# The configuration of app when it is exposed to the web.
web:
  locations:
    "/":
      # The public directory of the app, relative to its root.
      root: "public"
      # The front-controller script to send non-static requests to.
      passthru: "/index.php"


