blank_issues_enabled: false
contact_links:
  - name: Ask a question
    url: https://stackoverflow.com/questions/tagged/shopware6
    about: Get answers from a global community on all the technical questions that help you develop with Shopware.
  - name: Join us on community Slack
    url: https://slack.shopware.com
    about: You may want to reach the community chat